# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/eleves/Documents/Vivado_Design_Suite/ASCON_Implementation/ASCON_Implementation.srcs/sources_1/ip/ascon_datain_memory/ascon_datain_memory.xci
# IP: The module: 'ascon_datain_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eleves/Documents/Vivado_Design_Suite/ASCON_Implementation/ASCON_Implementation.gen/sources_1/ip/ascon_datain_memory/ascon_datain_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ascon_datain_memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/eleves/Documents/Vivado_Design_Suite/ASCON_Implementation/ASCON_Implementation.srcs/sources_1/ip/ascon_datain_memory/ascon_datain_memory.xci
# IP: The module: 'ascon_datain_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eleves/Documents/Vivado_Design_Suite/ASCON_Implementation/ASCON_Implementation.gen/sources_1/ip/ascon_datain_memory/ascon_datain_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ascon_datain_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
